//! Distributed discrete-Laplace publication inside the MPC.

use sha2::{Digest, Sha256};

const DOMAIN: &[u8] = b"QOMM:DISTRIBUTED-DP:v1";
pub const U64_SPACE: u128 = 1_u128 << 64;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DpMechanism {
    pub epsilon_micros: u64,
    pub sensitivity: u64,
    pub support: u16,
    pub version: String,
}

impl DpMechanism {
    pub fn new(epsilon_micros: u64, sensitivity: u64, support: u16) -> Result<Self, String> {
        if epsilon_micros == 0 || sensitivity == 0 {
            return Err("epsilon and sensitivity must be positive".into());
        }
        if !(1..=4096).contains(&support) {
            return Err("support must lie in 1..4096".into());
        }
        Ok(Self {
            epsilon_micros,
            sensitivity,
            support,
            version: "distributed-discrete-laplace-v1".into(),
        })
    }

    pub fn rounding_delta(&self) -> (u64, u128) {
        (2 * (2 * u64::from(self.support) + 1), U64_SPACE)
    }

    pub fn digest(&self) -> [u8; 32] {
        Sha256::new()
            .chain_update(DOMAIN)
            .chain_update(self.version.as_bytes())
            .chain_update(self.epsilon_micros.to_be_bytes())
            .chain_update(self.sensitivity.to_be_bytes())
            .chain_update(u32::from(self.support).to_be_bytes())
            .finalize()
            .into()
    }

    /// Quantised CDF endpoints over `[0, 2^64)`. The final endpoint is kept as
    /// `u128` because it is exactly one past `u64::MAX`.
    pub fn thresholds(&self) -> Result<Vec<u128>, String> {
        let epsilon = self.epsilon_micros as f64 / 1_000_000.0;
        let alpha = (-epsilon / self.sensitivity as f64).exp();
        let normalizer = (1.0 - alpha) / (1.0 + alpha);
        let support = i32::from(self.support);
        let tail = normalizer * alpha.powi(support) / (1.0 - alpha);
        let mut probabilities = Vec::with_capacity(usize::from(self.support) * 2 + 1);
        probabilities.push(tail);
        for value in (-support + 1)..support {
            probabilities.push(normalizer * alpha.powi(value.abs()));
        }
        probabilities.push(tail);
        let mut cumulative = 0.0_f64;
        let mut endpoints = Vec::with_capacity(probabilities.len());
        for (index, probability) in probabilities.iter().enumerate() {
            cumulative += probability;
            let endpoint = if index + 1 == probabilities.len() {
                U64_SPACE
            } else {
                (cumulative * U64_SPACE as f64).floor() as u128
            };
            if endpoints
                .last()
                .is_some_and(|previous| endpoint <= *previous)
            {
                return Err(
                    "64-bit CDF has a zero-probability cell; lower support or epsilon".into(),
                );
            }
            endpoints.push(endpoint);
        }
        Ok(endpoints)
    }

    pub fn sample_u64(&self, uniform: u64) -> Result<i32, String> {
        let endpoints = self.thresholds()?;
        let index = endpoints.partition_point(|endpoint| *endpoint <= u128::from(uniform));
        Ok(-i32::from(self.support) + index as i32)
    }

    pub fn mp_spdz_source(
        &self,
        n_parties: usize,
        budget_total_micros: u64,
        budget_spent_micros: u64,
        label: &str,
    ) -> Result<String, String> {
        if n_parties < 3 {
            return Err("distributed publication requires at least three nodes".into());
        }
        let after = budget_spent_micros
            .checked_add(self.epsilon_micros)
            .ok_or_else(|| "the requested release exceeds its privacy budget".to_string())?;
        if after > budget_total_micros {
            return Err("the requested release exceeds its privacy budget".into());
        }
        if label.is_empty()
            || !label
                .chars()
                .next()
                .is_some_and(|character| character == '_' || character.is_ascii_alphabetic())
            || !label
                .chars()
                .all(|character| character == '_' || character.is_ascii_alphanumeric())
        {
            return Err("output label must be a Python identifier".into());
        }
        let thresholds = self.thresholds()?;
        let comparisons = thresholds[..thresholds.len() - 1]
            .iter()
            .map(|threshold| format!("u.__ge__({threshold})"))
            .collect::<Vec<_>>()
            .join(" + ");
        Ok(format!(
            "# generated by qomm_audit.distributed_dp; do not edit\n\
             from Compiler.types import sint\n\
             N_PARTIES = {n_parties}\n\
             EPSILON_MICROS = {}\n\
             BUDGET_BEFORE_MICROS = {budget_spent_micros}\n\
             BUDGET_AFTER_MICROS = {after}\n\
             exact = sum(sint.get_input_from(p) for p in range(N_PARTIES))\n\
             random_bits = [sint.get_random_bit() for _ in range(64)]\n\
             u = sum(random_bits[j] * (1 << j) for j in range(64))\n\
             noise = -{} + ({comparisons})\n\
             {label} = exact + noise\n\
             print_ln('%s', {label}.reveal())\n",
            self.epsilon_micros, self.support
        ))
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct BudgetState {
    pub total_micros: u64,
    pub spent_micros: u64,
}

impl BudgetState {
    pub fn spend(self, mechanism: &DpMechanism) -> Result<Self, String> {
        let spent = self
            .spent_micros
            .checked_add(mechanism.epsilon_micros)
            .ok_or_else(|| "privacy budget exhausted".to_string())?;
        if spent > self.total_micros {
            return Err("privacy budget exhausted".into());
        }
        Ok(Self {
            total_micros: self.total_micros,
            spent_micros: spent,
        })
    }
}
