"""Distributed discrete-Laplace publication inside the MPC.

The production path emits an MP-SPDZ program.  Its exact aggregate and every
random bit are secret values; only ``exact + noise`` is opened.  MP-SPDZ creates
each random bit as a shared value, so no computing node learns the full random
draw.  The public CDF is quantised to 64 bits and the resulting rounding delta
is stated explicitly rather than silently calling the approximation pure DP.
"""

from __future__ import annotations

import bisect
import hashlib
from dataclasses import dataclass
from decimal import Decimal, localcontext

DOMAIN = b"QOMM:DISTRIBUTED-DP:v1"
U64 = 1 << 64


@dataclass(frozen=True)
class DpMechanism:
    epsilon_micros: int
    sensitivity: int
    support: int
    version: str = "distributed-discrete-laplace-v1"

    def __post_init__(self) -> None:
        if self.epsilon_micros <= 0 or self.sensitivity <= 0:
            raise ValueError("epsilon and sensitivity must be positive")
        if not 1 <= self.support <= 4096:
            raise ValueError("support must lie in 1..4096")

    @property
    def epsilon(self) -> Decimal:
        return Decimal(self.epsilon_micros) / Decimal(1_000_000)

    @property
    def rounding_delta(self) -> tuple[int, int]:
        # Each of 2M+1 cells moves by < 2^-64; comparing adjacent datasets can
        # double the total-variation allowance.
        return 2 * (2 * self.support + 1), U64

    @property
    def digest(self) -> bytes:
        return hashlib.sha256(
            DOMAIN + self.version.encode() + self.epsilon_micros.to_bytes(8, "big")
            + self.sensitivity.to_bytes(8, "big")
            + self.support.to_bytes(4, "big")).digest()

    def thresholds(self) -> tuple[int, ...]:
        """Upper CDF endpoints over ``[0, 2^64)`` for clipped noise."""

        with localcontext() as context:
            context.prec = 100
            alpha = (-self.epsilon / Decimal(self.sensitivity)).exp()
            normaliser = (Decimal(1) - alpha) / (Decimal(1) + alpha)
            tail = normaliser * (alpha ** self.support) / (Decimal(1) - alpha)
            probabilities = [tail]
            probabilities += [normaliser * alpha ** abs(k)
                              for k in range(-self.support + 1, self.support)]
            probabilities += [tail]
            cumulative = Decimal(0)
            thresholds = []
            for index, probability in enumerate(probabilities):
                cumulative += probability
                endpoint = U64 if index == len(probabilities) - 1 else int(cumulative * U64)
                if thresholds and endpoint <= thresholds[-1]:
                    raise ValueError(
                        "64-bit CDF has a zero-probability cell; lower support or epsilon")
                thresholds.append(endpoint)
            return tuple(thresholds)

    def sample_u64(self, uniform: int) -> int:
        """Clear reference only; production uses :meth:`mp_spdz_source`."""

        if not 0 <= uniform < U64:
            raise ValueError("uniform input must be a 64-bit unsigned integer")
        return -self.support + bisect.bisect_right(self.thresholds(), uniform)

    def mp_spdz_source(self, *, n_parties: int, budget_total_micros: int,
                       budget_spent_micros: int, label: str = "published") -> str:
        """Emit a fixed-shape circuit that opens only the noisy statistic.

        Each node supplies one share of the exact aggregate with
        ``sint.get_input_from``.  The shares are summed in secret.  Random bits
        come from MP-SPDZ's jointly generated secret randomness and are never
        printed.  A budget violation is rejected before any program is emitted.
        """

        if n_parties < 3:
            raise ValueError("distributed publication requires at least three nodes")
        after = budget_spent_micros + self.epsilon_micros
        if budget_spent_micros < 0 or after > budget_total_micros:
            raise ValueError("the requested release exceeds its privacy budget")
        if not label.isidentifier():
            raise ValueError("output label must be a Python identifier")
        thresholds = self.thresholds()[:-1]
        comparisons = " + ".join(
            f"u.__ge__({threshold})" for threshold in thresholds) or "0"
        lines = [
            "# generated by qomm_audit.distributed_dp; do not edit",
            "from Compiler.types import sint",
            f"N_PARTIES = {n_parties}",
            f"EPSILON_MICROS = {self.epsilon_micros}",
            f"BUDGET_BEFORE_MICROS = {budget_spent_micros}",
            f"BUDGET_AFTER_MICROS = {after}",
            "exact = sum(sint.get_input_from(p) for p in range(N_PARTIES))",
            "random_bits = [sint.get_random_bit() for _ in range(64)]",
            "u = sum(random_bits[j] * (1 << j) for j in range(64))",
            f"noise = -{self.support} + ({comparisons})",
            f"{label} = exact + noise",
            f"print_ln('%s', {label}.reveal())",
        ]
        return "\n".join(lines) + "\n"


@dataclass(frozen=True)
class BudgetState:
    total_micros: int
    spent_micros: int = 0

    def spend(self, mechanism: DpMechanism) -> "BudgetState":
        after = self.spent_micros + mechanism.epsilon_micros
        if after > self.total_micros:
            raise ValueError("privacy budget exhausted")
        return BudgetState(self.total_micros, after)
