//! Rendering a compiled deployment, so `REGULATION.md` section 8 stops being prose.
//!
//! The table there was written by hand and has drifted twice already: once when
//! a module was renamed and once when selective disclosure went from "a hook
//! the design can carry" to something built. A rendered table cannot drift,
//! because rendering it is the only way it exists.

use crate::{Compiled, Verdict};

pub fn markdown(compiled: &Compiled) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# {} in {} ({}), as of {}\n\n",
        compiled.instrument, compiled.jurisdiction_name, compiled.jurisdiction, compiled.as_of
    ));
    out.push_str(&format!(
        "Title is held in the **{}** register.\n\n",
        compiled.register
    ));

    out.push_str("## What the legal system has to provide\n\n");
    out.push_str("| | asks for | verdict | clause | in force | last reviewed |\n");
    out.push_str("| --- | --- | --- | --- | ---: | ---: |\n");
    for finding in &compiled.findings {
        let verdict = match finding.verdict {
            Verdict::Permitted => "**permitted**",
            Verdict::Conditional => "conditional",
            Verdict::Refused => "**refused**",
        };
        out.push_str(&format!(
            "| **{}** | {} | {} | {} | {} | {} |\n",
            finding.requirement,
            finding.says,
            verdict,
            finding.citation,
            finding.in_force,
            finding.reviewed
        ));
    }
    for finding in &compiled.findings {
        if !finding.note.is_empty() {
            out.push_str(&format!(
                "\n- **{}** --- {}\n",
                finding.requirement, finding.note
            ));
        }
    }

    let blocked = compiled.blocked_by();
    out.push('\n');
    if blocked.is_empty() {
        out.push_str("Nothing here refuses the deployment outright.\n");
    } else {
        out.push_str("**Refused outright**, and by which clause:\n\n");
        for finding in blocked {
            out.push_str(&format!(
                "- {} --- {} ({})\n",
                finding.requirement, finding.note, finding.citation
            ));
        }
    }

    out.push_str("\n## Which evidence discharges which obligation\n\n");
    out.push_str("| the operator must | discharged by | which is not good for |\n");
    out.push_str("| --- | --- | --- |\n");
    for duty in &compiled.duties {
        match &duty.undischarged {
            Some(why) => out.push_str(&format!("| {} | **nothing** | {} |\n", duty.says, why)),
            None => {
                let by = duty
                    .discharged_by
                    .iter()
                    .map(|(id, from, _)| format!("`{id}` ({from})"))
                    .collect::<Vec<_>>()
                    .join(", ");
                let not = duty
                    .discharged_by
                    .iter()
                    .flat_map(|(_, _, not)| not.iter().cloned())
                    .collect::<Vec<_>>()
                    .join("; ");
                out.push_str(&format!(
                    "| {} | {} | {} |\n",
                    duty.says,
                    by,
                    if not.is_empty() { "---".into() } else { not }
                ));
            }
        }
    }

    let undischarged = compiled.undischarged();
    if !undischarged.is_empty() {
        out.push_str(&format!(
            "\n**{} obligation(s) nothing here discharges.** They are written \
             down rather than absent, which is the difference between a gap and \
             an oversight.\n",
            undischarged.len()
        ));
    }
    out.push_str(
        "\nGenerated by `qomm-law`. Not legal advice, and not a claim \
                  that the clauses cited are current --- what it claims is that \
                  a clause nobody has reviewed inside its own interval stops the \
                  build rather than answering.\n",
    );
    out
}
