#!/usr/bin/env python3
"""What the range proofs would cost to assemble from shares, in rounds.

The quote proof is assembled jointly only for one Pedersen opening. The product
and bit steps could join it --- sigma responses are linear in the witness, so
the existing threshold machinery assembles them --- but the range proofs cannot,
because a range proof commits to each bit of the value and extracting bits needs
the value. That is recorded as an open problem, and an open problem with no cost
attached is one nobody can size.

This attaches a cost. Everything downstream of *having shares of the bits* is
already solved; the whole question is what producing those shares costs, and
over a wide area cost means rounds, since the wall clock is rounds times round
trip and very little else.

The arm that answers it is `compare_and_bits`. The circuit's `fits` and `fresh`
gates already compare exactly the differences the range proofs are about, and a
prime-field comparison decomposes internally --- so the marginal question is not
what a bit decomposition costs standing alone, but what it costs *on top of the
comparison already being paid for*. That difference is the number.

Measured with the instrument that produced the circuit's own round count: seven
parties, malicious Shamir at T=2, `-F 128`, and the runtime counter MP-SPDZ
prints as "Data sent = X MB in ~N rounds". A compile-time estimate is a
different number and is not comparable to it.

N = 48 is the operating point: sixteen makers times the three range proofs each
one needs.
"""
import argparse, json, re, subprocess, sys, time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.hosts import this_host                                # noqa: E402

RUNTIME_DATA = re.compile(r"Data sent\s*=\s*([\d.]+)\s*MB in ~([\d,]+) rounds", re.M)
RUNTIME_TIME = re.compile(r"^Time\s*=\s*([\d.]+)\s*seconds", re.M)
VM_ROUNDS = re.compile(r"([\d,]+)\s+virtual machine rounds")

BODIES = {
    # the floor: read the inputs and add them. Whatever this costs is not the
    # thing being measured, so it is subtracted rather than argued about.
    "inputs_only": "    keep.append(a + b)",
    # what the quote circuit does today
    "compare": "    keep.append((a < b).if_else(a, b))",
    # what a range proof needs from the nodes
    "bitdec": "    keep.append(sum((a - b).bit_decompose(BITS)))",
    # the comparison *and* the bits, to see whether they share the work. If a
    # prime-field comparison decomposes internally and throws the bits away,
    # this costs about what the comparison costs alone --- and the range proof's
    # bits are already being computed by the circuit today.
    "compare_and_bits": (
        "    bits = (a - b).bit_decompose(BITS)\n"
        "    keep.append((a < b).if_else(a, b) + sum(bits))"),
}

TEMPLATE = """# generated by bitdec_rounds.py --- {arm}, N={n}, {bits}-bit values
program.set_bit_length({bitlen})
program.use_edabit({edabit})

N = {n}
BITS = {bits}
keep = []
for i in range(N):
    a = sint.get_input_from(0)
    b = sint.get_input_from(1)
{body}

total = keep[0]
for x in keep[1:]:
    total = total + x
print_ln('%s', total.reveal())
"""


def inputs(root: Path, parties: int, count: int) -> None:
    """Every party needs a file; parties 0 and 1 need values to feed."""
    d = root / "Player-Data"
    d.mkdir(exist_ok=True)
    for p in range(parties):
        # comfortably inside 26 bits, and a > b so the comparison has work to do
        values = [str(1000 + 7 * i) if p == 0 else str(500 + 3 * i)
                  for i in range(count)]
        (d / f"Input-P{p}-0").write_text(" ".join(values) + "\n")


def one(root: Path, name: str, source: str, parties: int, threshold: int,
        binary: str) -> dict:
    (root / "Programs" / "Source" / f"{name}.mpc").write_text(source)
    out = subprocess.run([sys.executable, "./compile.py", "-F", "128", name],
                         cwd=root, capture_output=True, text=True)
    text = out.stdout + out.stderr
    if out.returncode != 0:
        return {"error": "compile: " + text.strip().splitlines()[-1]}
    row = {}
    m = VM_ROUNDS.search(text)
    if m:
        row["vm_rounds"] = int(m.group(1).replace(",", ""))

    procs = []
    t0 = time.perf_counter()
    for party in range(parties):
        procs.append(subprocess.Popen(
            [f"./{binary}", str(party), name, "-N", str(parties),
             "-T", str(threshold)],
            cwd=root, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True))
    outs = [p.communicate()[0] for p in procs]
    row["wall_seconds"] = time.perf_counter() - t0
    if any(p.returncode != 0 for p in procs):
        bad = next(o for p, o in zip(procs, outs) if p.returncode != 0)
        return {**row, "error": "run: " + bad.strip().splitlines()[-1][:200]}
    m = RUNTIME_DATA.search(outs[0])
    if m:
        row["mb"] = float(m.group(1))
        row["rounds"] = int(m.group(2).replace(",", ""))
    m = RUNTIME_TIME.search(outs[0])
    if m:
        row["seconds"] = float(m.group(1))
    return row


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--counts", type=int, nargs="+", default=[1, 16, 48])
    ap.add_argument("--bits", type=int, nargs="+", default=[26])
    ap.add_argument("--bitlen", type=int, default=128)
    ap.add_argument("--parties", type=int, default=7)
    ap.add_argument("--threshold", type=int, default=2)
    ap.add_argument("--repeats", type=int, default=5)
    ap.add_argument("--binary", default="malicious-shamir-party.x")
    args = ap.parse_args()

    inputs(args.root, args.parties, max(args.counts))
    rows = []
    for edabit in (False,):
        for arm, body in BODIES.items():
          for bits in args.bits:
            for n in args.counts:
                name = f"bdr_{arm}_{n}_{bits}_{'eda' if edabit else 'noeda'}"
                source = TEMPLATE.format(arm=arm, n=n, bits=bits,
                                         bitlen=args.bitlen, edabit=edabit,
                                         body=body)
                got = [one(args.root, name, source, args.parties,
                           args.threshold, args.binary)
                       for _ in range(args.repeats)]
                ok = [g for g in got if "rounds" in g]
                row = {"arm": arm, "n": n, "edabit": edabit, "bits": bits,
                       "repeats": len(ok)}
                if ok:
                    row["rounds"] = sorted(g["rounds"] for g in ok)[len(ok) // 2]
                    row["mb"] = sorted(g["mb"] for g in ok)[len(ok) // 2]
                    row["seconds"] = sorted(g["seconds"] for g in ok)[len(ok) // 2]
                    row["rounds_spread"] = [min(g["rounds"] for g in ok),
                                            max(g["rounds"] for g in ok)]
                else:
                    row["error"] = got[0].get("error", "no round count")
                row["vm_rounds"] = got[0].get("vm_rounds")
                rows.append(row)
                print(f"{arm:17s} N={n:3d} bits={bits:3d} -> "
                      f"rounds={row.get('rounds')} mb={row.get('mb')} "
                      f"s={row.get('seconds')} {row.get('error','')}", flush=True)
    marginal = {}
    for bits in args.bits:
        for n in args.counts:
            base = next((r for r in rows if r["arm"] == "compare"
                         and r["n"] == n and r["bits"] == bits), None)
            both = next((r for r in rows if r["arm"] == "compare_and_bits"
                         and r["n"] == n and r["bits"] == bits), None)
            if base and both and "rounds" in base and "rounds" in both:
                marginal[f"{bits}bit_n{n}"] = {
                    "comparison_alone": base["rounds"],
                    "comparison_and_bits": both["rounds"],
                    "extra_rounds": both["rounds"] - base["rounds"],
                    "extra_mb": round(both["mb"] - base["mb"], 3)}
    args.out.write_text(json.dumps({"host": this_host(), "bits": args.bits,
                                    "parties": args.parties,
                                    "threshold": args.threshold,
                                    "binary": args.binary,
                                    "marginal": marginal, "rows": rows},
                                   indent=1) + "\n")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
